### ISSUE TITLE
Lack of Detailed Documentation on MIG Configuration in Quickstart Guide

### ISSUE THREAD

**Issue by anencore94** [NVIDIA/k8s-dra-driver#105]
## Issue Description

The `quickstart/README.md` in the `demo/specs/quickstart` directory currently includes brief comments on setting up for a "real" deployment but lacks comprehensive details necessary for effective use, particularly regarding Multi-Instance GPU (MIG) configuration.

## Affected Files

- `demo/specs/quickstart/README.md`

## Specific Problems

1. **Insufficient Details for MIG Setup in Kind Cluster**:
   The examples under `demo/specs/quickstart` (e.g., `gpu-test4`, `gpu-test5`, `gpu-test6`) require MIG to be enabled. However, there's no detailed instruction on how to configure the MIG-related options properly. Consequently, without the correct setup, deploying these examples results in failures.

## Suggested Enhancements

1. **Expanded README with MIG Setup Instructions**:
   It would be highly beneficial for users if the README includes a detailed section on setting up MIG in a kind cluster environment. This should cover:

   - Prerequisites for enabling MIG, including required tools and initial environment setup.
   - Step-by-step guide on configuring MIG using `nvidia-mig-parted` or similar tools.
   - Examples of commands and configurations that have been proven to work in similar setups.
   - Troubleshooting common issues that might arise during the setup.

Just applying the following doesn't work for my cluster

   ```bash
   cat <<EOF | sudo -E nvidia-mig-parted apply -f -
   version: v1
   mig-configs:
      half-half:
      - devices: [0,1,2,3]
         mig-enabled: false
      - devices: [4,5,6,7]
         mig-enabled: true
         mig-devices: {}
   EOF

**Comment by klueska** [comment]
We will get there eventually -- the current focus is on stabilizing the API for DRA in upstream Kubernetes so that we can eventually build a production ready version of this driver. Until we have that, everything here is just a POC.

That said, I'm happy to help debug your setup in the meantime and / or accept a PR that improves the (intermediate) documentation.

The `mig-parted` command you show should be sufficient to get the GPUs in a state that the DRA driver can work with. What problems are you running into exactly?

**Comment by anencore94** [comment]
@klueska Hi, Thanks for the reply.

![image](https://github.com/NVIDIA/k8s-dra-driver/assets/37469330/684b39ec-ba65-465e-bfef-0419dbb76534)

My situation is as follows:

1. two different GPU models in kind cluster's worker node
2. apply nvidia-mig-parted with config file from https://github.com/NVIDIA/mig-parted/blob/main/examples/config.yaml
3. 2. succeed with `echo $? = 0`, but it doesn't work
4. Therefore, when I do `kubectl apply -f gpu-test4.yaml`, all pods, resourceclaims stay in Pending status, and there doesn't occur any mig instances by `nvidia-smi` in the worker node.

**Comment by klueska** [comment]
I believe the `1g.5gb` profile is not available on the RTX (they have profiles of different sizes), which one can query with:
```
nvidia-smi mig -lgip
```
The `mig-parted` command should probably not return success if an invalid profile is passed, but currently it just skips any GPUs where the profile is unavailable (so if none of the GPUs have it available it will just return success, (indicating that all GPUs supporting that profile were able to be updated successfully, which in this case is 0).

All of that said -- for DRA you should only apply the `all-enabled` config and nothing else. MIG device creation is done dynamically as requests come in, rather than preconfigured apriori.

**Comment by anencore94** [comment]
Thanks for the fast reply 🙏 
However, also the `all-enabled` config is not applied I believe.
![image](https://github.com/NVIDIA/k8s-dra-driver/assets/37469330/fc9e65ad-4583-4ca3-a1a3-ba05fe3904f5)


Even if the `all-enabled` config is with value `mig-enabled: true` as follows:
![image](https://github.com/NVIDIA/k8s-dra-driver/assets/37469330/9d8b8f27-d18f-4e1e-a70a-086a1c676ffc)

**Comment by klueska** [comment]
Are your GPUs mig capable? What does the output of `nvidia-smi mig -lgip` show in terms of available MIG profiles?

**Comment by anencore94** [comment]
> Are your GPUs mig capable? What does the output of `nvidia-smi mig -lgip` show in terms of available MIG profiles?

Thanks for the check. As you can see in the above screenshots, there wasn't any MIG-enabled devices. And `nvidia-smi -mig 1` doesn't work on my VMs. So maybe it is not MIG-capable in my VM GPUs.
I'll check it out. Thanks again.
